// conf/templates/tcdt_rust/web_ui/components/toolbar/FormToolBar.tsx
import { FC, useEffect, useState } from 'react';
import { Button, Space } from 'antd';
import { Observer, TMessage } from '@/util/observer';
import { subject, actionFormConf, } from '../../conf';

const FormToolBar: FC<{
  idLayout: string
  /**组件是否是禁用状态 */
  fgDisabled: boolean;
}> = ({ idLayout, fgDisabled }) => {
  const [componentFgDiabled, setComponentFgDiabled] = useState<boolean>(fgDisabled);
  const [fgAdd, setFgAdd] = useState<boolean>(true);

  useEffect(() => {
    setComponentFgDiabled(fgDisabled);
  }, [fgDisabled]);

  useEffect(() => {
    const toAddObserver: Observer = {
      topic: 'toAdd',
      consumerId: idLayout,
      update: function (message: TMessage): void {
        if (message.consumerIds.includes(idLayout)) {
          return;
        }
        setFgAdd(true);
      },
    };
    subject.subscribe(toAddObserver);

    const toEditObserver: Observer = {
      topic: 'toEdit',
      consumerId: idLayout,
      update: function (message: TMessage): void {
        if (message.consumerIds.includes(idLayout)) {
          return;
        }
        setFgAdd(false);
      },
    };
    subject.subscribe(toEditObserver);

    //销毁观察者
    return () => {
      subject.unsubsribe(toAddObserver);
      subject.unsubsribe(toEditObserver);
    };
  }, []);

  const handleSave = () => {
    if (fgAdd) {
      subject.publish({
        topic: 'add',
        producerId: idLayout,
        data: undefined,
      });
    } else {
      subject.publish({
        topic: 'edit',
        producerId: idLayout,
        data: undefined,
      });
    }
  };

  const handleAddAgain = () => {
    subject.publish({
      topic: 'addAgain',
      producerId: idLayout,
      data: undefined,
    });
  };

  const handleCancel = () => {
    subject.publish({
      topic: 'cancle',
      producerId: idLayout,
      data: undefined,
    });
  };

  const handleReflesh = () => {
    subject.publish({
      topic: 'detailReflesh',
      producerId: idLayout,
      data: undefined,
    });
  };

  return (
    <>
      <div
{%- raw %}
          style={{
            display: 'flex',
            flex: '0 1 auto',
            gap: actionFormConf?.gap ?? '10px',
            justifyContent: actionFormConf?.justifyContent ?? 'start',
            flexWrap: 'wrap',
          }}
{%- endraw %}
        >
{%- if rootInfo.buttonJson and rootInfo.buttonJson.buttons is iterable %}
  {%- for buttonConf in rootInfo.buttonJson.buttons %}
          <Button
            key={'{{ buttonConf.idButton }}'}
            size={'{{ buttonConf.buttonSize }}'}
            type={'{{ buttonConf.type }}'}
    {%- if buttonConf.disableScript %}
            disabled={{ "{" }}{{ buttonConf.disableScript }}{{ "}" }}
    {%- endif %}
            onClick={{ "{" }}{{ buttonConf.clickEventName }}{{ "}" }}
    {%- if buttonConf.hiddenScript %}
            hidden={{ "{" }}{{ buttonConf.hiddenScript }}{{ "}" }}
    {%- endif %}
          >
            {'{{ buttonConf.label }}'}
          </Button>
  {%- endfor %}
{%- endif %}
        </div>
    </>
  );
};

export default FormToolBar;

// conf/templates/demo_mybatis/web_ui/components/toolbar/FormToolBar.vue
<template>
  <div class="flex">
    <el-button type="primary" :icon="Plus" @click="handleSave">保存</el-button>
    <el-button v-if="fgAddRef" type="primary" :icon="Edit" @click="handleAddAgain">保存并新增</el-button>
    <el-button type="primary" @click="handleReflesh">刷新</el-button>
    <el-button type="primary" @click="handleCancel">返回</el-button>
  </div>
</template>
<script setup lang="ts">
const props = defineProps<{
  idLayout: string;
  /**组件是否是禁用状态 */
  fgDisabled: boolean;
}>();
import { Plus, Edit, } from '@element-plus/icons-vue'
import { ref, onMounted, onBeforeUnmount } from 'vue';
import { Observer, TMessage } from '~/util/observer';
import { subject } from '../../conf';

const compontId = 'formToolBar';
const fgAddRef = ref<boolean>(true);
const observers: Observer[] = [];
onMounted(() => {
  const toAddObserver: Observer = {
    topic: 'toAdd',
    consumerId: compontId,
    update: function (message: TMessage): void {
      if (message.consumerIds.includes(compontId)) {
        return;
      }
      fgAddRef.value = true;
    },
  };
  subject.subscribe(toAddObserver);
  observers.push(toAddObserver)

  const toEditObserver: Observer = {
    topic: 'toEdit',
    consumerId: compontId,
    update: function (message: TMessage): void {
      if (message.consumerIds.includes(compontId)) {
        return;
      }
      fgAddRef.value = false;
    },
  };
  subject.subscribe(toEditObserver);
  observers.push(toEditObserver)

});

onBeforeUnmount(() => {
  //销毁观察者
  observers.forEach(observer => subject.unsubsribe(observer))
})

const handleSave = () => {
  if (fgAddRef.value) {
    subject.publish({
      topic: 'add',
      data: undefined,
      producerId: props.idLayout,
    });
  } else {
    subject.publish({
      topic: 'edit',
      data: undefined,
      producerId: props.idLayout,
    });
  }
};

const handleAddAgain = () => {
  subject.publish({
    topic: 'addAgain',
    data: undefined,
    producerId: props.idLayout,
  });
};

const handleCancel = () => {
  subject.publish({
    topic: 'cancle',
    data: undefined,
    producerId: props.idLayout,
  });
};

const handleReflesh = () => {
  subject.publish({
    topic: 'detailReflesh',
    data: undefined,
    producerId: props.idLayout,
  });
};

</script>
